[phases.setup]
nixPkgs = ['...', 'nodejs']

[phases.build]
# This command installs the browser binaries AND required Linux system libraries
cmds = ['npm install', 'npx playwright install',    'npm playwright install --with-deps chromium']
